version: '3'
services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: liveticker
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build: ./server
    command: 