version: '3'
services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: liveticker
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      - ELGG_SECRET=$ELGG_SECRET
      - ELGG_ADMIN=$ELGG_ADMIN
      - DATABASE_URL=postgres://admin:admin@postgres:5432/liveticker
    build: ./
  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
    - '10022:80'
    - '25565:1935'
